
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123

development:
  <<: *default
  database: chat_application
production:
  <<: *default
  database: chat_application
